linux + guides additions
wailsapp/docsv1 pull request #1
Opened 2019-09-14 15:39 UTC by bh90210

2019-09-15 04:26 UTC, leaanthony requested changes

2019-09-15 04:26 UTC, leaanthony commented on content/gettingstarted/linux.md
> +_If you don't see your distro in the lists bellow you have two options. Either open a ticket asking for support or if you feel adventurus follow the [guide how to add support for your linux distro]({
Do you think this would be better if we shifted it below the Community supported distro list? I think it reads better that way?

2019-09-15 04:26 UTC, leaanthony commented on content/guides/yarn.md
> ++++
This is going to be a little harder than this article suggests. To speed builds up, the package.json is md5'ed and this is checked on build to see if there has been any updates. I think we'll need to put this on hold for a bit.

2019-09-25 00:18 UTC, bh90210 commented
uh dont bother reviewing it just yet, I found a typo and I need to add one more guide :+1:

2019-10-03 19:34 UTC, leaanthony reviewed
What's the public directory for? Is this just generated docs?

2019-10-06 08:24 UTC, bh90210 commented
uh sorry I just saw the comment

`public` is generated when running `hugo`, from hugo's docs

### The hugo Command 
The most common usage is probably to run hugo with your current directory being the input directory.

This generates your website to the public/ directory by default, although you can customize the output directory in your site configuration by changing the `publishDir` field.

I accidentally ran/pull it.
Fixed

2019-10-23 11:14 UTC, merged